<?php return array (
  'october\\demo\\Plugin' => 'plugins\\october\\demo\\Plugin.php',
  'backend\\Controllers\\index' => 'modules\\backend\\controllers\\index.php',
  'backend\\Controllers\\auth' => 'modules\\backend\\controllers\\auth.php',
  'system\\Controllers\\settings' => 'modules\\system\\controllers\\settings.php',
  'system\\Controllers\\updates' => 'modules\\system\\controllers\\updates.php',
  'cms\\Controllers\\themes' => 'modules\\cms\\controllers\\themes.php',
  'rainlab\\blog\\Plugin' => 'plugins\\rainlab\\blog\\Plugin.php',
  'martin\\forms\\Plugin' => 'plugins\\martin\\forms\\Plugin.php',
  'Martin\\Forms\\Models\\Record' => 'plugins\\martin\\forms\\models\\Record.php',
  'RainLab\\Blog\\Models\\Post' => 'plugins\\rainlab\\blog\\models\\Post.php',
  'RainLab\\Blog\\Classes\\TagProcessor' => 'plugins\\rainlab\\blog\\classes\\TagProcessor.php',
  'RainLab\\Blog\\Models\\Category' => 'plugins\\rainlab\\blog\\models\\Category.php',
  'Martin\\Forms\\Models\\Settings' => 'plugins\\martin\\forms\\models\\Settings.php',
  'Martin\\Forms\\Classes\\BackendHelpers' => 'plugins\\martin\\forms\\classes\\BackendHelpers.php',
  'Martin\\Forms\\Classes\\UnreadRecords' => 'plugins\\martin\\forms\\classes\\UnreadRecords.php',
  'cms\\Controllers\\themeoptions' => 'modules\\cms\\controllers\\themeoptions.php',
);